### PR TITLE
MINOR: Development

### PR DESCRIPTION
**Pull request by kenudeh**
I've removed the `/calculate-card-stats` endpoint from `statistics.md` and rearranged the endpoints in `goal.md` to reflect the new order of things in `goal.py`. Meanwhile, it appears that `/get-weekly-xp` and `get-total-xp` were never part of the docs at any point.

### CODE REVIEW

**Comment by jacob-macleod** [comment]
Hi there, thanks for the pull request. Is this to resolve https://github.com/jacob-macleod/Dolphin-Flashcard-App/issues/125? If so, are the docs in mintlify format?

Also, I've added `MINOR: ` to the start of the MR, which tells the pipeline what type of change it is, so it can check the version has been updated correctly

**Comment by kenudeh** [comment]
No, it's not for Mintlify, that'll be ready soon. This PR is for the API method that was taken out from the docs.

**Comment by jacob-macleod** [comment]
Ah great thanks. Please could you update the version number in `__init__.py`? This is probably a MINOR change, which is defined by the `MINOR: ` at the start of the MR title, so the new version should be `3.5.0`

Please could you also document the changes and the new version in `CHANGELOG.md`, following the existing style there? Thanks

Once you've done that, the pipelines should pass, and I'll merge

**Comment by kenudeh** [comment]
Alright, I'll do those today.

**Pull request closed without merging**
